# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniele/tesla/tesla-static-analysis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniele/tesla/tesla-static-analysis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniele/tesla/tesla-static-analysis/CMakeFiles /home/daniele/tesla/tesla-static-analysis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniele/tesla/tesla-static-analysis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named run-demos

# Build rule for target.
run-demos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-demos
.PHONY : run-demos

# fast build rule for target.
run-demos/fast:
	$(MAKE) -f demos/CMakeFiles/run-demos.dir/build.make demos/CMakeFiles/run-demos.dir/build
.PHONY : run-demos/fast

#=============================================================================
# Target rules for targets named tesla

# Build rule for target.
tesla: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tesla
.PHONY : tesla

# fast build rule for target.
tesla/fast:
	$(MAKE) -f libtesla/src/CMakeFiles/tesla.dir/build.make libtesla/src/CMakeFiles/tesla.dir/build
.PHONY : tesla/fast

#=============================================================================
# Target rules for targets named repeat.cpp.test

# Build rule for target.
repeat.cpp.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 repeat.cpp.test
.PHONY : repeat.cpp.test

# fast build rule for target.
repeat.cpp.test/fast:
	$(MAKE) -f libtesla/test/CMakeFiles/repeat.cpp.test.dir/build.make libtesla/test/CMakeFiles/repeat.cpp.test.dir/build
.PHONY : repeat.cpp.test/fast

#=============================================================================
# Target rules for targets named match.cpp.test

# Build rule for target.
match.cpp.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 match.cpp.test
.PHONY : match.cpp.test

# fast build rule for target.
match.cpp.test/fast:
	$(MAKE) -f libtesla/test/CMakeFiles/match.cpp.test.dir/build.make libtesla/test/CMakeFiles/match.cpp.test.dir/build
.PHONY : match.cpp.test/fast

#=============================================================================
# Target rules for targets named lookup.cpp.test

# Build rule for target.
lookup.cpp.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lookup.cpp.test
.PHONY : lookup.cpp.test

# fast build rule for target.
lookup.cpp.test/fast:
	$(MAKE) -f libtesla/test/CMakeFiles/lookup.cpp.test.dir/build.make libtesla/test/CMakeFiles/lookup.cpp.test.dir/build
.PHONY : lookup.cpp.test/fast

#=============================================================================
# Target rules for targets named store.c.test

# Build rule for target.
store.c.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 store.c.test
.PHONY : store.c.test

# fast build rule for target.
store.c.test/fast:
	$(MAKE) -f libtesla/test/CMakeFiles/store.c.test.dir/build.make libtesla/test/CMakeFiles/store.c.test.dir/build
.PHONY : store.c.test/fast

#=============================================================================
# Target rules for targets named actions.cpp.test

# Build rule for target.
actions.cpp.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 actions.cpp.test
.PHONY : actions.cpp.test

# fast build rule for target.
actions.cpp.test/fast:
	$(MAKE) -f libtesla/test/CMakeFiles/actions.cpp.test.dir/build.make libtesla/test/CMakeFiles/actions.cpp.test.dir/build
.PHONY : actions.cpp.test/fast

#=============================================================================
# Target rules for targets named libtesla-test

# Build rule for target.
libtesla-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libtesla-test
.PHONY : libtesla-test

# fast build rule for target.
libtesla-test/fast:
	$(MAKE) -f libtesla/test/CMakeFiles/libtesla-test.dir/build.make libtesla/test/CMakeFiles/libtesla-test.dir/build
.PHONY : libtesla-test/fast

#=============================================================================
# Target rules for targets named update.cpp.test

# Build rule for target.
update.cpp.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update.cpp.test
.PHONY : update.cpp.test

# fast build rule for target.
update.cpp.test/fast:
	$(MAKE) -f libtesla/test/CMakeFiles/update.cpp.test.dir/build.make libtesla/test/CMakeFiles/update.cpp.test.dir/build
.PHONY : update.cpp.test/fast

#=============================================================================
# Target rules for targets named tesla-analyse

# Build rule for target.
tesla-analyse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tesla-analyse
.PHONY : tesla-analyse

# fast build rule for target.
tesla-analyse/fast:
	$(MAKE) -f tesla/analyser/CMakeFiles/tesla-analyse.dir/build.make tesla/analyser/CMakeFiles/tesla-analyse.dir/build
.PHONY : tesla-analyse/fast

#=============================================================================
# Target rules for targets named TeslaCommon

# Build rule for target.
TeslaCommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TeslaCommon
.PHONY : TeslaCommon

# fast build rule for target.
TeslaCommon/fast:
	$(MAKE) -f tesla/common/CMakeFiles/TeslaCommon.dir/build.make tesla/common/CMakeFiles/TeslaCommon.dir/build
.PHONY : TeslaCommon/fast

#=============================================================================
# Target rules for targets named TeslaProto

# Build rule for target.
TeslaProto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TeslaProto
.PHONY : TeslaProto

# fast build rule for target.
TeslaProto/fast:
	$(MAKE) -f tesla/common/CMakeFiles/TeslaProto.dir/build.make tesla/common/CMakeFiles/TeslaProto.dir/build
.PHONY : TeslaProto/fast

#=============================================================================
# Target rules for targets named LLVMTesla

# Build rule for target.
LLVMTesla: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LLVMTesla
.PHONY : LLVMTesla

# fast build rule for target.
LLVMTesla/fast:
	$(MAKE) -f tesla/instrumenter/CMakeFiles/LLVMTesla.dir/build.make tesla/instrumenter/CMakeFiles/LLVMTesla.dir/build
.PHONY : LLVMTesla/fast

#=============================================================================
# Target rules for targets named tesla-test

# Build rule for target.
tesla-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tesla-test
.PHONY : tesla-test

# fast build rule for target.
tesla-test/fast:
	$(MAKE) -f tesla/test/CMakeFiles/tesla-test.dir/build.make tesla/test/CMakeFiles/tesla-test.dir/build
.PHONY : tesla-test/fast

#=============================================================================
# Target rules for targets named tesla-cat

# Build rule for target.
tesla-cat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tesla-cat
.PHONY : tesla-cat

# fast build rule for target.
tesla-cat/fast:
	$(MAKE) -f tesla/tools/cat/CMakeFiles/tesla-cat.dir/build.make tesla/tools/cat/CMakeFiles/tesla-cat.dir/build
.PHONY : tesla-cat/fast

#=============================================================================
# Target rules for targets named tesla-get-triple

# Build rule for target.
tesla-get-triple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tesla-get-triple
.PHONY : tesla-get-triple

# fast build rule for target.
tesla-get-triple/fast:
	$(MAKE) -f tesla/tools/get-triple/CMakeFiles/tesla-get-triple.dir/build.make tesla/tools/get-triple/CMakeFiles/tesla-get-triple.dir/build
.PHONY : tesla-get-triple/fast

#=============================================================================
# Target rules for targets named tesla-print

# Build rule for target.
tesla-print: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tesla-print
.PHONY : tesla-print

# fast build rule for target.
tesla-print/fast:
	$(MAKE) -f tesla/tools/print/CMakeFiles/tesla-print.dir/build.make tesla/tools/print/CMakeFiles/tesla-print.dir/build
.PHONY : tesla-print/fast

#=============================================================================
# Target rules for targets named tesla-archive

# Build rule for target.
tesla-archive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tesla-archive
.PHONY : tesla-archive

# fast build rule for target.
tesla-archive/fast:
	$(MAKE) -f tesla/tools/archive/CMakeFiles/tesla-archive.dir/build.make tesla/tools/archive/CMakeFiles/tesla-archive.dir/build
.PHONY : tesla-archive/fast

#=============================================================================
# Target rules for targets named tesla-extract

# Build rule for target.
tesla-extract: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tesla-extract
.PHONY : tesla-extract

# fast build rule for target.
tesla-extract/fast:
	$(MAKE) -f tesla/tools/extract/CMakeFiles/tesla-extract.dir/build.make tesla/tools/extract/CMakeFiles/tesla-extract.dir/build
.PHONY : tesla-extract/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... intrinsics_gen"
	@echo "... check"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... run-demos"
	@echo "... tesla"
	@echo "... repeat.cpp.test"
	@echo "... match.cpp.test"
	@echo "... lookup.cpp.test"
	@echo "... store.c.test"
	@echo "... actions.cpp.test"
	@echo "... libtesla-test"
	@echo "... update.cpp.test"
	@echo "... tesla-analyse"
	@echo "... TeslaCommon"
	@echo "... TeslaProto"
	@echo "... LLVMTesla"
	@echo "... tesla-test"
	@echo "... tesla-cat"
	@echo "... tesla-get-triple"
	@echo "... tesla-print"
	@echo "... tesla-archive"
	@echo "... tesla-extract"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

